### ISSUE TITLE
UX on chat prompts

### ISSUE THREAD

**Issue by MikeBorman1** [Growthautomation/moneyfitt#26] opened 2024-10-09 03:40 UTC
The suggestions - it is a little annoying how the moment I click off the application, e.g. onto whatsapp, they are gone and replaced by three new ones - if I liked one then I now have lost it

Should be on load page generate some, then only on a new advisor message generate new ones and always display them

**Comment by yeaung276** [comment] 2024-10-09 04:33
duplicate of #12 please track that issue

**Closed by yeaung276** 2024-10-09 04:33 UTC
